package presentationLayer;

import businessLayer.*;
import dataLayer.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * Class used for creating the Administrator GUI and having a table to see the base and composite products
 * with their prices
 * @author Loga Darius
 */
public class AdministratorGUI extends javax.swing.JFrame {

    private Restaurant restaurant;

    /**
     * Creates new form AdministratorGUI
     * @param restaurant for specifying the type of the
     */
    public AdministratorGUI(Restaurant restaurant) {
        this.restaurant = restaurant;
        initComponents();
        setVisible(true);
    }
    public static boolean isStringOnlyAlphabet(String str, int ok) //validations for the inputs using regex
    { 
        if(ok == 0) 
        {return ((str != null) 
                && (!str.equals("")) 
                && (str.matches("^[a-zA-Z]*$")));
        }
        if(ok == 1){
            return ((str != null) 
                && (!str.equals("")) 
                && (str.matches("^[0-9]*$")));}
        if(ok == 2){
            return ((str != null) 
                && (!str.equals("")) 
                && (str.matches("^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$")));}
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        baseProductName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        baseProductPrice = new javax.swing.JTextField();
        createBaseProduct = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        compositeProductName = new javax.swing.JTextField();
        compositeComponent = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addComponent = new javax.swing.JButton();
        createCompositeProduct = new javax.swing.JButton();
        editName = new javax.swing.JLabel();
        editNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        newPrice = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        deleteField = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        view = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator");

        jLabel1.setText("MenuItem Name");

        jLabel2.setText("MenuItem Price");

        createBaseProduct.setText("Create Base Product");
        createBaseProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createBaseProductMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Composite Product Name");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Composite Product Component");

        addComponent.setText("Add");
        addComponent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addComponentMouseClicked(evt);
            }
        });

        createCompositeProduct.setActionCommand("");
        createCompositeProduct.setLabel("Create Composite Product");
        createCompositeProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createCompositeProductMouseClicked(evt);
            }
        });

        editName.setText("Edit MenuItem Name");

        jLabel5.setText("New Price");

        edit.setText("Edit MenuItem");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Delete MenuItem Name");

        delete.setText("Delete MenuItem");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        view.setText("View");
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(compositeProductName)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(baseProductName)
                                    .addComponent(baseProductPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createBaseProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(compositeComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(addComponent))
                                .addComponent(createCompositeProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(editNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(editName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(newPrice)))
                                .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteField)
                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(baseProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(baseProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(createBaseProduct)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compositeProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compositeComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addComponent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createCompositeProduct)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editName)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete))
                    .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Methods designed for making use of the buttons in the GUI
     * to proper add/delete/edit products
     * @param evt the event happening
     */
    private void createBaseProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBaseProductMouseClicked
        String name = baseProductName.getText();
        double price = Double.parseDouble(baseProductPrice.getText());
        if(!isStringOnlyAlphabet(name, 0) || (price == 0 || price < 0)) {JOptionPane.showMessageDialog(null, "No correct input!", "Error", JOptionPane.ERROR_MESSAGE, null);}
        else{
        MenuItem item = new MenuItem(name, price);
        restaurant.addMenuItem(item);
        JOptionPane.showMessageDialog(null, "Created 1 BASE PRODUCT", "UI Info", JOptionPane.INFORMATION_MESSAGE, null);
        RestaurantSerializator.serialize(restaurant);
        }
    }//GEN-LAST:event_createBaseProductMouseClicked

    private CompositeProduct compItem = new CompositeProduct();
    private void addComponentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addComponentMouseClicked
        String name = compositeProductName.getText();
        if(!isStringOnlyAlphabet(name, 0)) {JOptionPane.showMessageDialog(null, "No correct input!", "Error", JOptionPane.ERROR_MESSAGE, null);}
        else{
        compItem.setName(name);
        String compName = compositeComponent.getText();
        MenuItem item = restaurant.findMenuItem(compName);
        if (item != null) {
            compItem.addCompItem(item);
            JOptionPane.showMessageDialog(null, "Created 1 COMPONENT", "UI Info", JOptionPane.INFORMATION_MESSAGE, null);
        } else {
            JOptionPane.showMessageDialog(null, "There is no menu item having the name: " + compName, "ErrorCompItem", JOptionPane.WARNING_MESSAGE, null);
        }

        }
    }//GEN-LAST:event_addComponentMouseClicked

    private void createCompositeProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createCompositeProductMouseClicked
        compItem.setPrice(compItem.computePrice());
        restaurant.addMenuItem(compItem);
        JOptionPane.showMessageDialog(null, "Created 1 COMPOSITE PRODUCT", "UI Info", JOptionPane.INFORMATION_MESSAGE, null);
        compItem = null;
        RestaurantSerializator.serialize(restaurant);
    }//GEN-LAST:event_createCompositeProductMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        String name = editNameField.getText();
        double price = Double.parseDouble(newPrice.getText());
        if(!isStringOnlyAlphabet(name, 0) || (price == 0 || price < 0)) {JOptionPane.showMessageDialog(null, "No correct input!", "Error", JOptionPane.ERROR_MESSAGE, null);}
        else{MenuItem item = new MenuItem();
        item.setName(name);
        restaurant.editMenuItem(item, price);
        JOptionPane.showMessageDialog(null, "Edited 1 PRODUCT", "UI Info", JOptionPane.INFORMATION_MESSAGE, null);
        RestaurantSerializator.serialize(restaurant);}
    }//GEN-LAST:event_editMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        String name = deleteField.getText();
        if(!isStringOnlyAlphabet(name, 0)) {JOptionPane.showMessageDialog(null, "No correct input!", "Error", JOptionPane.ERROR_MESSAGE, null);}
        else{restaurant.removeMenuItem(name);
        JOptionPane.showMessageDialog(null, "Deleted 1 PRODUCT", "UI Info", JOptionPane.INFORMATION_MESSAGE, null);
        RestaurantSerializator.serialize(restaurant);}
    }//GEN-LAST:event_deleteMouseClicked

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (MenuItem item : restaurant.getItems()) {
            Object[] row = { item.getName(), item.computePrice()};
            model.addRow(row);
            jTable1 = new JTable(model);
            jScrollPane1.add(jTable1);
        }
    }//GEN-LAST:event_viewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Restaurant r = new Restaurant();
                new AdministratorGUI(r).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComponent;
    private javax.swing.JTextField baseProductName;
    private javax.swing.JTextField baseProductPrice;
    private javax.swing.JTextField compositeComponent;
    private javax.swing.JTextField compositeProductName;
    private javax.swing.JButton createBaseProduct;
    private javax.swing.JButton createCompositeProduct;
    private javax.swing.JButton delete;
    private javax.swing.JTextField deleteField;
    private javax.swing.JButton edit;
    private javax.swing.JLabel editName;
    private javax.swing.JTextField editNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField newPrice;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}